main = ".worker-next/index.mjs"
name = "nodejs-website"
compatibility_date = "2024-11-07"
compatibility_flags = ["nodejs_compat"]
assets = { directory = ".worker-next/assets", binding = "ASSETS" }
account_id = "fb4a2d0f103c6ff38854ac69eb709272"
