main = ".worker-next/index.mjs"
name = "nodejs-website"
compatibility_date = "2024-11-07"
compatibility_flags = ["nodejs_compat"]
account_id = "fb4a2d0f103c6ff38854ac69eb709272"

[observability]
enabled = true
head_sampling_rate = 1

[alias]
"node:fs" = "./.cloudflare/node/fs.mjs"
"node:fs/promises" = "./.cloudflare/node/fs/promises.mjs"

[vars]
PAGES = 'pages'
